# GitHub Pages Configuration for Static Site

# Disable Jekyll processing for static HTML site
plugins: []

# Build settings
source: main branch
destination: / (root)

# SEO settings
title: Don Richardson Bayya - Portfolio
description: Professional portfolio showcasing Data Engineering, Analytics, and Data Science projects
author: Don Richardson Bayya
email: donrichardsonbayya@gmail.com
url: https://YOUR_AZURE_STATIC_WEB_APP_URL
baseurl: ""

# Social links
social:
  github: donrichardsonbayya
  linkedin: donrichardsonbayya
  twitter: donrichardsonbayya

# Analytics (optional)
# google_analytics: UA-XXXXXXXXX-X
